# Generated by Django 6.0.7 on 2026-09-15 17:51

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            # Historical storefront amounts were USD. Do not relabel them when a
            # deployment later selects BDT for new orders.
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Payment succeeded but fulfillment needs manual review.'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order', name='currency',
            field=models.CharField(default=orders.models.default_currency, max_length=3),
        ),
    ]
